# This is a basic workflow to help you get started with Actions

name: Terraform Setup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ARM_CLIENT_ID: "${{ secrets.CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.TENANT_ID }}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job contains a single job for terraform init, validate and plan
  tf-plan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment:
      name: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3

      # - uses: Azure/login@v1
      #   with:
      #     creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'


      - name: terraform init
        run: |
          cd cloud_infra_app 
          cd scripts 
          chmod 777 init.sh
          cd .. 
          scripts/init.sh 

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: |
          cd cloud_infra_app/scripts 
          chmod 777 plan.sh
          cd .. 
          scripts/plan.sh 

      - name: upload plan.out
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan-artifact
          path: cloud_infra_app/plan.out

      - name: list files
        run: cd cloud_infra_app && ls
        
  
  # This job for terraform apply
  tf-apply:
    runs-on: ubuntu-latest

    needs: tf-plan

    environment:
      name: dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3

      - uses: actions/download-artifact@v3
        with:
          name: tf-plan-artifact
          path: cloud_infra_app     
      
      - name: list files
        run: cd cloud_infra_app && ls -a

      - name: terraform init
        run: |
          cd cloud_infra_app 
          cd scripts 
          chmod 777 init.sh
          cd .. 
          scripts/init.sh 

      - name: terraform apply
        run: |
          cd cloud_infra_app/scripts 
          chmod 777 apply.sh
          cd .. 
          scripts/apply.sh         